package Constants;

public class cromaConstants {
    public static final String SHIP_NODE = "D001";
    public static final String ORDER_NUMBER = "EC20240827002";
    public static final String SHIPMENT_NO = "107913748";
    public static final String ANSI_RESET = "\u001B[0m";
    public static final String ANSI_YELLOW = "\u001B[33m";
    public static final String BaseURL="http://10.34.32.29/:9080/";
    public static final String PORT = "http://10.34.32.29:9080/wsc/store/login.do";
    public static final String ResourceURLCroma="/smcfs/yfshttpapi/yantrahttpapitester.jsp";
    public static final String USERNAME = "username";
    public static final String PASSWORD = "//div[@class='form-group']//input[@id='password']";
    public static final String LOGIN = "//*[@id=\"loginBtn\"]";
    public static final String GET_ORDER_DETAILS="getOrderDetails";
    public static final String CONTINUE_PACKING = "//span[@isc-i18n='shipmentsummary.ACTION_ContinuePackShipment']";
    public static final String ORDER_NUMBER_FOR_RTS = "pick_shipmentOrderBarcodeScanner";
    public static final String SEARCH_ORDER_NUMBER_FOR_RTS = "//button[@title='Scan or enter order or shipment #']";
    public static final String CLICK_ON_PICK_ORDER_BUTTON = "//*[@id=\"mainContentHolder\"]/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/button/span[2]";
    public static final String PICK_OK_BUTTON = "//*[@id=\"bodyTagId\"]/div[1]/div/div/footer/div/button";
    public static final String FINISH_PICK_BUTTON = "//span[normalize-space()='Finish Pick']";
    public static final String VIEW_ALL_SHIPMENT_BUTTON = "//*[text()='View All Shipments']";
    public static final String FILTER_BUTTON = "//*[@id=\"filterBtn\"]/span[1]";
    public static final String CLICK_ON_ORDER_NUMBER_IN_FILTER = "//*[@id=\"mainContentHolder\"]/div[2]/div/div/div[2]/div[1]/div/isc-view-all-shipments-filter/div/div[1]/div/div[2]/div/div/section/uib-accordion/div/div[4]/div[1]/h4/a/span/span[2]";
    public static final String TYPE_ORDER_NUMBER = "//*[@id=\"mainContentHolder\"]/div[2]/div/div/div[2]/div[1]/div/isc-view-all-shipments-filter/div/div[1]/div/div[2]/div/div/section/uib-accordion/div/div[4]/div[2]/div/div/input";
    public static final String APPLY_BUTTON = "//button[@type='submit']";
    public static final String UPDATE_CARRIER_AND_VOLUMETRICS_BUTTON = "//button[normalize-space()='Update carrier & volumetrics']";
    public static final String UPDATE_CARRIER_AND_VOLUMETRICS_OK_BUTTON = "//*[@id=\"okBtn\"]";
    public static final String FINISH_PACKING_BUTTON = "//span[normalize-space()='Finish Pack']";
    public static final String PRINT_AWB_BUTTON = "//span[normalize-space()='Print AWB']";
    public static final String PRINT_INVOICE_BUTTON = "//span[normalize-space()='Print Invoice']";
    public static final String CONNECT_TO_CARRIER_BUTTON = "//*[@id=\"mainContentHolder\"]/div[2]/div/div/div[1]/div[2]/div/div[3]/button";
    public static final String CONNECT_TO_CARRIER_OK_BUTTON = "//*[@id=\"bodyTagId\"]/div[1]/div/div/footer/div/button";
    public static final String CLICK_ON_DONE_BUTTON = "//*[@id=\"mainContentHolder\"]/div[2]/div/div/div[1]/div[2]/div/div[3]/button/span[2]";
    public static final String STORE_HOME_PAGE_TEXT = "//*[text()='What do you want to do?']";
    public static final String SHIPMENT_NUMBER_EXPAND = "//div[@is-open='ui.accordianConfig.showShipmentNo']//span[@title='Expand']";
    public static final String TYPE_SHIPMENT_NUMBER = "//input[@ng-model='ui.filterCriteria.shipmentNo']";
    public static final String STATUS_EXPAND = "//span[@class='grp-hdr-txt'][normalize-space()='Status']";
    public static final String STATUS_DROPDOWN = "//div[5]//div[2]//div[1]//div[1]//div[1]//div[1]//div[1]//select[1]";
    public static final String STATUS_VALUE = "//*[text()='Connect To Carrier']";
    public static final String CARRIER_EXPAND = "//span[@class='grp-hdr-txt'][normalize-space()='Carrier']";
    public static final String CARRIER_DROPDOWN = "//select[@id='shipment_carrier']";
    public static final String CARRIER_VALUE = "//*[text()='Delhivery']";
    public static final String CITY_EXPAND = "//span[contains(text(),'City')]";
    public static final String TYPE_CITY = "//input[contains(@ng-model,'ui.filterCriteria.city')]";
    public static final String LP_MODE_EXPAND = "//span[contains(@class,'grp-hdr-txt')][normalize-space()='LP Mode']";
    public static final String LP_MODE_DROPDOWN = "//div[contains(@class,'panel-collapse in collapse')]//select[@id='lp_mode']";
    public static final String SELECT_CHECK_BOX = "//*[@id=\"addressCheck_$index\"]";
    public static final String HANDOVER_SHIPMENTS_BUTTON = "//*[@id=\"mainContentHolder\"]/div[2]/div/div/div[1]/div[2]/div/div[2]/button/span";
    public static final String HANDOVER_SHIPMENTS_OK_BUTTON = "//*[@id=\"bodyTagId\"]/div[1]/div/div/footer/div/button/span";
    public static final String DELIVERY_IN_PROGRESS_BUTTON = "//*[@id=\"mainContentHolder\"]/div[2]/div/div/div[1]/div[2]/div/div[4]/button/span";
    public static final String DELIVERY_IN_PROGRESS_OK_BUTTON = "//*[@id=\"bodyTagId\"]/div[1]/div/div/footer/div/button";
    public static final String OUT_FOR_DELIVER_BUTTON = "//*[@id=\"mainContentHolder\"]/div[2]/div/div/div[1]/div[2]/div/div[3]/button/span";
    public static final String OUT_FOR_DELIVERY_OK_BUTTON = "//*[@id=\"bodyTagId\"]/div[1]/div/div/footer/div/button/span";
    public static final String DELIVERED_BUTTON = "//*[@id=\"mainContentHolder\"]/div[2]/div/div/div[1]/div[2]/div/div[3]/button/span";
    public static final String DELIVERED_OK_BUTTON = "//*[@id=\"bodyTagId\"]/div[1]/div/div/footer/div/button";
    public static final String CLICK_ON_HOTC = "//*[text()='HOTC']";
    public static final String CLICK_ON_DIP = "//*[text()='DIP']";
    public static final String CLICK_ON_DELIVERED = "//*[text()='Delivered']";
    public static final String CLICK_ON_OUT_FOR_DELIVERY = "//*[text()='Out For Delivery']";
    public static final String PICK_ORDER_HOME_PAGE = "//*[@id=\"appTitle\"]";
    public static final String INTEROPAPINAME="InteropApiName";
    public static final String FLOW="IsFlow";
    public static final String FLOW_PARAMTER_VALUE="N";
    public static final String SERVICE_NAME="ServiceName";
    public static final String USERID="YFSEnvironment.userId";
    public static final String ADMIN="admin";
    public static final String PASSWORD_VALUE="password";
    public static final String INTEROPAPIDATA="InteropApiData";
    public static final String PICK_ORDER_PAGE="//*[@id=\"mainContentHolder\"]/div[2]/div/div[2]/div/div[1]/div/div[1]/div[2]/span";
    public static final String SHIPMENT_SUMMERY_PAGE="//*[@id=\"mainContentHolder\"]/div[2]/div/div/div[1]/div[1]/div[2]/span";
    public static final String PACK_ORDER_PAGE="//*[@id=\"mainContentHolder\"]/div[2]/div/div[2]/div/div/div[1]/div[1]/div[2]/span";
    public static final String WEIGHT="//*[@id=\"bodyTagId\"]/div[1]/div/div/section/div/div[1]/div/input";
    public static final String HEIGHT="//*[@id=\"bodyTagId\"]/div[1]/div/div/section/div/div[2]/div/input";
    public static final String LENGTH="//*[@id=\"bodyTagId\"]/div[1]/div/div/section/div/div[3]/div/input";
    public static final String WIDTH="//*[@id=\"bodyTagId\"]/div[1]/div/div/section/div/div[4]/div/input";
    public static final String CARRIER="//*[@id=\"container.Carrier_label\"]/span[2]";
    public static final String CARRIER_VALUE_FOR_UCV="//*[text()='Delhivery - 1 Day Freight']";
    public static final String SHIPMENT_SEARCH_RESULTS_PAGE="//*[@id=\"mainContentHolder\"]/div[2]/div/div/div[1]/div[1]/span";
//    public static final String PACK_ORDER_PAGE="";
//    public static final String PACK_ORDER_PAGE="";
}
